# 2025-26 Project - Foundations of Computer Science

**Project by:**
- Herandez, Nicole Winy </br>
- Ortega, Azriel Matthew </br>
- Tibayan, Meryann Joy

In [2]:
# import libraries
import pandas as pd
import os

### 1. Create a single dataframe with the concatenation of all input csv files, adding a column called country

In [3]:
# read csv files with read_csv function from pandas
videos_folder = "videos"

df_cavideos = pd.read_csv(f"{videos_folder}/CAvideos.csv")
df_devideos = pd.read_csv(f"{videos_folder}/DEvideos.csv")
df_frvideos = pd.read_csv(f"{videos_folder}/FRvideos.csv")
df_gbvideos = pd.read_csv(f"{videos_folder}/GBvideos.csv")
df_invideos = pd.read_csv(f"{videos_folder}/INvideos.csv")
df_usvideos = pd.read_csv(f"{videos_folder}/USvideos.csv")

# TO DO: Experiment with these 4 CSV Files with different encoding to see which has the best result

# UPDATE 1: After experimenting, it seems that using default encoding(utf-8) and using encoding errors
# to skip some bytes that cant be read is better than finding a specific encoding for each language
# However, this must be researched more for example: If this only a computer specific problem, or 
# there is a way to read everything properly without having to use encoding errors

df_jpvideos = pd.read_csv(f"{videos_folder}/JPvideos.csv", encoding="utf-8", encoding_errors="replace", engine="python")
df_krvideos = pd.read_csv(f"{videos_folder}/KRvideos.csv", encoding="utf-8", encoding_errors="replace", engine="python")
df_mxvideos = pd.read_csv(f"{videos_folder}/MXvideos.csv", encoding="utf-8", encoding_errors="replace", engine="python")
df_ruvideos = pd.read_csv(f"{videos_folder}/RUvideos.csv", encoding="utf-8", encoding_errors="replace", engine="python")

They say it is hard to determine the correct encoding for each text file, especially if it is not utf-8 </br>
Reference https://community.dataquest.io/t/how-do-we-know-the-encoding-to-use-with-pd-read-csv-chardet-doesnt-help/467614/4 </br>

You have to do trial and error with all of the encodings to check which one works best. As for my testing 11/20/2025, utf-8 is best for all with the encoding_errors set to replace.

Here is the docs for checking all encodings : https://docs.python.org/3/library/codecs.html#standard-encodings

In [4]:
# Efficient code version (with concatenation process

# Import all csv files, read and compile them into one dataframe
# With the addition of adding a new column 'country' to determine from what csv file it came from

dataframe_lists = []
for file in os.listdir(videos_folder):
    if file[9:] == "csv":
        print(f"Reading {file}")
        df_temp = pd.read_csv(f"{videos_folder}/{file}", encoding_errors="replace")
        df_temp["country"] = file[:2] # add country column
        dataframe_lists.append(df_temp)

df_videos = pd.concat(dataframe_lists) # concatenate everything into one dataframe
df_videos = df_videos.reset_index(drop=True) # reset index

Reading MXvideos.csv
Reading INvideos.csv
Reading DEvideos.csv
Reading JPvideos.csv
Reading KRvideos.csv
Reading CAvideos.csv
Reading RUvideos.csv
Reading FRvideos.csv
Reading USvideos.csv
Reading GBvideos.csv

In [5]:
df_videos

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,SbOwzAl9ZfQ,17.14.11,Capítulo 12 | MasterChef 2017,MasterChef 2017,24,2017-11-13T06:06:22.000Z,"MasterChef Junior 2017|""TV Azteca""|""recetas""|""...",310130,4182,361,1836,https://i.ytimg.com/vi/SbOwzAl9ZfQ/default.jpg,False,False,False,Disfruta la presencia del Chef Torreblanca en ...,MX
1,klOV6Xh-DnI,17.14.11,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,Micky Contreras Martinez,22,2017-11-13T05:11:58.000Z,La Voz Mexico 7,104972,271,174,369,https://i.ytimg.com/vi/klOV6Xh-DnI/default.jpg,False,False,False,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,MX
2,6L2ZF7Qzsbk,17.14.11,LOUIS CKAGÓ - EL PULSO DE LA REPÚBLICA,El Pulso De La República,25,2017-11-13T17:00:02.000Z,"Chumel Torres|""El Pulso de la Republica""|""noti...",136064,10105,266,607,https://i.ytimg.com/vi/6L2ZF7Qzsbk/default.jpg,False,False,False,La canción del principio se llama “Este espíri...,MX
3,hcY52MFWMDM,17.14.11,Sismo de 6.7 sacude Costa Rica 12 Noviembre 2017,Casanare,25,2017-11-13T03:47:10.000Z,"temblor|""costa rica""|""sismo en costa rica""",96153,378,171,208,https://i.ytimg.com/vi/hcY52MFWMDM/default.jpg,False,False,False,El video es de un Walmart en el pais centroame...,MX
4,_OXDcGPVAa4,17.14.11,DOG HACKS | MUSAS LESSLIE LOS POLINESIOS,Musas,26,2017-11-13T19:17:48.000Z,"MUSAS|""lesslie""|""karen""|""hacks""|""perros""|""dogs...",499965,57781,681,7428,https://i.ytimg.com/vi/_OXDcGPVAa4/default.jpg,False,False,False,MI HERMANO NARRA MI RUTINA DE MAQUILLAJE\nhttp...,MX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,l884wKofd54,18.14.06,Enrique Iglesias - MOVE TO MIAMI (Official Vid...,EnriqueIglesiasVEVO,10,2018-05-09T07:00:01.000Z,"Enrique Iglesias feat. Pitbull|""MOVE TO MIAMI""...",25066952,268088,12783,9933,https://i.ytimg.com/vi/l884wKofd54/default.jpg,False,False,False,NEW SONG - MOVE TO MIAMI feat. Pitbull (Click ...,GB
375938,IP8k2xkhOdI,18.14.06,Jacob Sartorius - Up With It (Official Music V...,Jacob Sartorius,10,2018-05-11T17:09:16.000Z,"jacob sartorius|""jacob""|""up with it""|""jacob sa...",1492219,61998,13781,24330,https://i.ytimg.com/vi/IP8k2xkhOdI/default.jpg,False,False,False,THE OFFICIAL UP WITH IT MUSIC VIDEO!Get my new...,GB
375939,Il-an3K9pjg,18.14.06,Anne-Marie - 2002 [Official Video],Anne-Marie,10,2018-05-08T11:05:08.000Z,"anne|""marie""|""anne-marie""|""2002""|""two thousand...",29641412,394830,8892,19988,https://i.ytimg.com/vi/Il-an3K9pjg/default.jpg,False,False,False,Get 2002 by Anne-Marie HERE ▶ http://ad.gt/200...,GB
375940,-DRsfNObKIQ,18.14.06,Eleni Foureira - Fuego - Cyprus - LIVE - First...,Eurovision Song Contest,24,2018-05-08T20:32:32.000Z,"Eurovision Song Contest|""2018""|""Lisbon""|""Cypru...",14317515,151870,45875,26766,https://i.ytimg.com/vi/-DRsfNObKIQ/default.jpg,False,False,False,Eleni Foureira represented Cyprus at the first...,GB
375941,4YFo4bdMO8Q,18.14.06,KYLE - Ikuyo feat. 2 Chainz & Sophia Black [A...,SuperDuperKyle,10,2018-05-11T04:06:35.000Z,"Kyle|""SuperDuperKyle""|""Ikuyo""|""2 Chainz""|""Soph...",607552,18271,274,1423,https://i.ytimg.com/vi/4YFo4bdMO8Q/default.jpg,False,False,False,Debut album 'Light of Mine' out now: http://ky...,GB

### 2. Extract all videos that have no tag.

### 3. For each channel, determine the total number of views

### 4. Save all rows with disabled comments and disabled ratings, or that have video_error_or_removed in a new dataframe called excluded, and remove those rows from the original dataframe.

In [6]:
df_videos_disabled = df_videos[df_videos["comments_disabled"] | df_videos["video_error_or_removed"]]
df_videos = df_videos.drop(df_videos_disabled.index)

### 5. Add a like_ratio column storing the ratio between the number of likes and of dislikes

### 6. Cluster the publish time into 10-minute intervals (e.g. from 02:20 to 02:30)

### 7. For each interval, determine the number of videos, average number of likes and of dislikes.

### 8. For each tag, determine the number of videos. Notice that tags contains a string with several tags

In [7]:
# Setup tag column in our dataframe first
df_videos["tags"] = df_videos["tags"].str.split('|') # Split the string into array with '|' as the separator

# Explode dataframe so that each row wiill have one tag, it will duplicate rows with many tags
# This is the approach because it is useful when grouping by tags.
df_videos_tags_explode = df_videos.explode('tags')

In [8]:
# clean dataset by removing all extra characters such as double quotations (")
df_videos_tags_explode["tags"] = df_videos_tags_explode["tags"].str.replace('"', '')

In [9]:
df_videos_tags_explode["tags"].value_counts()

tags
[none]                         36370
funny                          14945
comedy                         12303
2018                           10991
news                            6067
                               ...
extreme chinese street food        1
pamtri                             1
nutshell                           1
nan                                1
straw hand                         1
Name: count, Length: 840346, dtype: int64

### 9. Find the tags with the largest number of videos

In [10]:
df_videos_tags_explode.groupby(by="tags")["views"].sum()

tags
                                                   357327734
 #Freeticket                                         1761155
 #Jaisimha                                           1761155
 #JanaSenaParty                                       582282
 #MahaaNews                                           440239
                                                     ...
😜😜                                                     31787
😥                                                      44089
😭 #résistancelamaindesqueezie ❤️                       19781
😭قفز عسكري الوحيد من الطائرة العسكرية الجزائرية      1234013
🤝 ZARBEX zahlt Schutzgeld!!!                           29535
Name: views, Length: 840346, dtype: int64

### 10. For each (tag, country) pair, compute average ratio likes/dislikes

In [11]:
# TO DO: UNCOMMENT CODE BELOW ONCE 5 5 IS FINISHED
# pd.DataFrame(df_videos_tags_explode.groupby(by=["tags","country"])["like_dislike_ratio"].mean()) <- Needs table from 5

### 11. For each (trending_date, country) pair, the video with the largest number of views

### 12. Divide trending_date into three columns: year, month, day

In [12]:
# 1. Suddividi la colonna 'trending_date'
# Il parametro expand=True trasforma il risultato in un DataFrame
data_split = df_videos['trending_date'].str.split('.', expand=True)

# 2. Assegna le nuove colonne
# Indice 0 = Anno (YY) -> aggiungiamo '20' per avere '2017'
df_videos['year'] = '20' + data_split[0].astype(str)
# Indice 1 = Giorno (DD)
df_videos['day'] = data_split[1]
# Indice 2 = Mese (MM)
df_videos['month'] = data_split[2]

# Verifica il risultato
print(df_videos[['video_id','trending_date', 'year', 'month', 'day']].head())

      video_id trending_date  year month day
0  SbOwzAl9ZfQ      17.14.11  2017    11  14
1  klOV6Xh-DnI      17.14.11  2017    11  14
2  6L2ZF7Qzsbk      17.14.11  2017    11  14
3  hcY52MFWMDM      17.14.11  2017    11  14
4  _OXDcGPVAa4      17.14.11  2017    11  14

In [13]:
# 1. Conversione in formato datetime
# Utilizza il formato corretto che sembra essere 'YY.DD.MM'
df_videos['trending_date'] = pd.to_datetime(df_videos['trending_date'], format='%y.%d.%m')

# 2. Estrazione delle componenti
df_videos['year'] = df_videos['trending_date'].dt.year
df_videos['month'] = df_videos['trending_date'].dt.month
df_videos['day'] = df_videos['trending_date'].dt.day

# Stampa le prime righe per verificare il risultato
print(df_videos[['trending_date', 'year', 'month', 'day']].head())

  trending_date  year  month  day
0    2017-11-14  2017     11   14
1    2017-11-14  2017     11   14
2    2017-11-14  2017     11   14
3    2017-11-14  2017     11   14
4    2017-11-14  2017     11   14

### 13. For each (month, country) pair, the video with the largest number of views

In [24]:
# 1. Raggruppa per 'month' e 'country'
# 2. Trova l'indice della riga con il valore 'views' più alto in ogni gruppo
max_views_indices = df_videos.groupby(['month', 'country'])['views'].idxmax()

# 3. Usa gli indici trovati per selezionare le righe complete dal DataFrame originale
df_max_views = df_videos.loc[max_views_indices]

# Visualizza il risultato
print(df_max_views[['month', 'country', 'video_id','title', 'views']].head())

        month country     video_id  \
184947      1      CA  LsoLEjrDogU
88852       1      DE  LsoLEjrDogU
266485      1      FR  LsoLEjrDogU
349789      1      GB  LsoLEjrDogU
52495       1      IN  dfnCAmr569k

                                                    title     views
184947  Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...  43067983
88852   Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...  37728802
266485  Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...  37728802
349789  Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...  90598955
52495      Taylor Swift - End Game ft. Ed Sheeran, Future  42019590

### 14. Read all json files with the video categories

In [25]:
import os
import json
import pandas as pd

json_folder = 'categories'
df_list = []

for file in os.listdir(json_folder):
    if file.endswith(".json"):
        print(f"Reading {file}")
        
        with open(os.path.join(json_folder, file), 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        # Normalizzazione corretta per YouTube categories
        df_temp = pd.json_normalize(data['items'])
        
        # Selezioniamo solo le colonne utili
        df_temp = df_temp[['id', 'snippet.title', 'snippet.assignable']]
        
        # Rinominiamo per coerenza con dataframe video
        df_temp.columns = ['category_id', 'category_name', 'assignable']
        
        # Convertiamo category_id in numero intero
        df_temp['category_id'] = df_temp['category_id'].astype(int)
        
        df_list.append(df_temp)

df_categories = pd.concat(df_list, ignore_index=True)

df_categories

Reading IN_category_id.json
Reading RU_category_id.json
Reading JP_category_id.json
Reading FR_category_id.json
Reading GB_category_id.json
Reading KR_category_id.json
Reading MX_category_id.json
Reading CA_category_id.json
Reading US_category_id.json
Reading DE_category_id.json

     category_id     category_name  assignable
0              1  Film & Animation        True
1              2  Autos & Vehicles        True
2             10             Music        True
3             15    Pets & Animals        True
4             17            Sports        True
..           ...               ...         ...
306           40    Sci-Fi/Fantasy       False
307           41          Thriller       False
308           42            Shorts       False
309           43             Shows       False
310           44          Trailers       False

[311 rows x 3 columns]

### 15. For each country, determine how many videos have a category that is not assignable

In [ ]:
df_merged = df_videos.merge(df_categories, on='category_id', how='left')
df_not_assignable = (df_merged[df_merged['assignable'] == False]
    .groupby('country')['video_id']
    .count()
    .reset_index(name='non_assignable_count')
)
print(df_not_assignable)

country
CA    1300
DE    1020
FR    1100
GB     200
IN    2210
KR    1670
MX      30
RU    1830
US     570
Name: video_id, dtype: int64