# 2025-26 Project - Foundations of Computer Science

**Project by:**
- Herandez, Nicole Winy </br>
- Ortega, Azriel Matthew </br>
- Tibayan, Meryann Joy

In [1]:
# import libraries
import pandas as pd
import os

### 1. Create a single dataframe with the concatenation of all input csv files, adding a column called country

In [2]:
# read csv files with read_csv function from pandas
videos_folder = "videos"

df_cavideos = pd.read_csv(f"{videos_folder}/CAvideos.csv")
df_devideos = pd.read_csv(f"{videos_folder}/DEvideos.csv")
df_frvideos = pd.read_csv(f"{videos_folder}/FRvideos.csv")
df_gbvideos = pd.read_csv(f"{videos_folder}/GBvideos.csv")
df_invideos = pd.read_csv(f"{videos_folder}/INvideos.csv")
df_usvideos = pd.read_csv(f"{videos_folder}/USvideos.csv")

# TO DO: Experiment with these 4 CSV Files with different encoding to see which has the best result

# UPDATE 1: After experimenting, it seems that using default encoding(utf-8) and using encoding errors
# to skip some bytes that cant be read is better than finding a specific encoding for each language
# However, this must be researched more for example: If this only a computer specific problem, or 
# there is a way to read everything properly without having to use encoding errors

df_jpvideos = pd.read_csv(f"{videos_folder}/JPvideos.csv", encoding="utf-8", encoding_errors="replace", engine="python")
df_krvideos = pd.read_csv(f"{videos_folder}/KRvideos.csv", encoding="utf-8", encoding_errors="replace", engine="python")
df_mxvideos = pd.read_csv(f"{videos_folder}/MXvideos.csv", encoding="utf-8", encoding_errors="replace", engine="python")
df_ruvideos = pd.read_csv(f"{videos_folder}/RUvideos.csv", encoding="utf-8", encoding_errors="replace", engine="python")

They say it is hard to determine the correct encoding for each text file, especially if it is not utf-8 </br>
Reference https://community.dataquest.io/t/how-do-we-know-the-encoding-to-use-with-pd-read-csv-chardet-doesnt-help/467614/4 </br>

You have to do trial and error with all of the encodings to check which one works best. As for my testing 11/20/2025, utf-8 is best for all with the encoding_errors set to replace.

Here is the docs for checking all encodings : https://docs.python.org/3/library/codecs.html#standard-encodings

In [3]:
# Efficient code version (with concatenation process

# Import all csv files, read and compile them into one dataframe
# With the addition of adding a new column 'country' to determine from what csv file it came from

dataframe_lists = []
for file in os.listdir(videos_folder):
    if file[9:] == "csv":
        print(f"Reading {file}")
        df_temp = pd.read_csv(f"{videos_folder}/{file}", encoding_errors="replace")
        df_temp["country"] = file[:2] # add country column
        dataframe_lists.append(df_temp)

df_videos = pd.concat(dataframe_lists) # concatenate everything into one dataframe
df_videos = df_videos.reset_index(drop=True) # reset index

Reading MXvideos.csv
Reading INvideos.csv
Reading DEvideos.csv
Reading JPvideos.csv
Reading KRvideos.csv
Reading CAvideos.csv
Reading RUvideos.csv
Reading FRvideos.csv
Reading USvideos.csv
Reading GBvideos.csv

In [4]:
df_videos

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,SbOwzAl9ZfQ,17.14.11,Capítulo 12 | MasterChef 2017,MasterChef 2017,24,2017-11-13T06:06:22.000Z,"MasterChef Junior 2017|""TV Azteca""|""recetas""|""...",310130,4182,361,1836,https://i.ytimg.com/vi/SbOwzAl9ZfQ/default.jpg,False,False,False,Disfruta la presencia del Chef Torreblanca en ...,MX
1,klOV6Xh-DnI,17.14.11,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,Micky Contreras Martinez,22,2017-11-13T05:11:58.000Z,La Voz Mexico 7,104972,271,174,369,https://i.ytimg.com/vi/klOV6Xh-DnI/default.jpg,False,False,False,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,MX
2,6L2ZF7Qzsbk,17.14.11,LOUIS CKAGÓ - EL PULSO DE LA REPÚBLICA,El Pulso De La República,25,2017-11-13T17:00:02.000Z,"Chumel Torres|""El Pulso de la Republica""|""noti...",136064,10105,266,607,https://i.ytimg.com/vi/6L2ZF7Qzsbk/default.jpg,False,False,False,La canción del principio se llama “Este espíri...,MX
3,hcY52MFWMDM,17.14.11,Sismo de 6.7 sacude Costa Rica 12 Noviembre 2017,Casanare,25,2017-11-13T03:47:10.000Z,"temblor|""costa rica""|""sismo en costa rica""",96153,378,171,208,https://i.ytimg.com/vi/hcY52MFWMDM/default.jpg,False,False,False,El video es de un Walmart en el pais centroame...,MX
4,_OXDcGPVAa4,17.14.11,DOG HACKS | MUSAS LESSLIE LOS POLINESIOS,Musas,26,2017-11-13T19:17:48.000Z,"MUSAS|""lesslie""|""karen""|""hacks""|""perros""|""dogs...",499965,57781,681,7428,https://i.ytimg.com/vi/_OXDcGPVAa4/default.jpg,False,False,False,MI HERMANO NARRA MI RUTINA DE MAQUILLAJE\nhttp...,MX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,l884wKofd54,18.14.06,Enrique Iglesias - MOVE TO MIAMI (Official Vid...,EnriqueIglesiasVEVO,10,2018-05-09T07:00:01.000Z,"Enrique Iglesias feat. Pitbull|""MOVE TO MIAMI""...",25066952,268088,12783,9933,https://i.ytimg.com/vi/l884wKofd54/default.jpg,False,False,False,NEW SONG - MOVE TO MIAMI feat. Pitbull (Click ...,GB
375938,IP8k2xkhOdI,18.14.06,Jacob Sartorius - Up With It (Official Music V...,Jacob Sartorius,10,2018-05-11T17:09:16.000Z,"jacob sartorius|""jacob""|""up with it""|""jacob sa...",1492219,61998,13781,24330,https://i.ytimg.com/vi/IP8k2xkhOdI/default.jpg,False,False,False,THE OFFICIAL UP WITH IT MUSIC VIDEO!Get my new...,GB
375939,Il-an3K9pjg,18.14.06,Anne-Marie - 2002 [Official Video],Anne-Marie,10,2018-05-08T11:05:08.000Z,"anne|""marie""|""anne-marie""|""2002""|""two thousand...",29641412,394830,8892,19988,https://i.ytimg.com/vi/Il-an3K9pjg/default.jpg,False,False,False,Get 2002 by Anne-Marie HERE ▶ http://ad.gt/200...,GB
375940,-DRsfNObKIQ,18.14.06,Eleni Foureira - Fuego - Cyprus - LIVE - First...,Eurovision Song Contest,24,2018-05-08T20:32:32.000Z,"Eurovision Song Contest|""2018""|""Lisbon""|""Cypru...",14317515,151870,45875,26766,https://i.ytimg.com/vi/-DRsfNObKIQ/default.jpg,False,False,False,Eleni Foureira represented Cyprus at the first...,GB
375941,4YFo4bdMO8Q,18.14.06,KYLE - Ikuyo feat. 2 Chainz & Sophia Black [A...,SuperDuperKyle,10,2018-05-11T04:06:35.000Z,"Kyle|""SuperDuperKyle""|""Ikuyo""|""2 Chainz""|""Soph...",607552,18271,274,1423,https://i.ytimg.com/vi/4YFo4bdMO8Q/default.jpg,False,False,False,Debut album 'Light of Mine' out now: http://ky...,GB

### 2. Extract all videos that have no tag.

In [7]:
no_tag_videos = df_videos[
    (df_videos["tags"].isna()) |
    (df_videos["tags"] == "") |
    (df_videos["tags"] == "[none]")
]

no_tag_videos

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
5,Q9kK6NWZR1U,17.14.11,Asi se sintio Terremoto en iraq al bordo de ir...,MÚSICA & ENTRETENIMIENTO,10,2017-11-12T20:17:38.000Z,[none],129645,506,67,239,https://i.ytimg.com/vi/Q9kK6NWZR1U/default.jpg,False,False,False,Un fuerte sismo ha afectado en la noche de est...,MX
19,7D-swI6qNLM,17.14.11,HACKS CON SILICÓN CALIENTE,MaireWink,24,2017-11-13T18:00:01.000Z,[none],217025,26934,201,1277,https://i.ytimg.com/vi/7D-swI6qNLM/default.jpg,False,False,False,CANAL DE HISTORIAS:\nhttps://www.youtube.com/H...,MX
25,nEAMm3nGxpM,17.14.11,El valiente ve la muerte solo una vez - Teaser,Agencia Bengala,1,2017-11-13T13:32:23.000Z,[none],7127,37,3,13,https://i.ytimg.com/vi/nEAMm3nGxpM/default.jpg,False,False,False,"A lo largo de su vida, Alejo Garza Tamez ha cu...",MX
38,cgYhR-3QfhM,17.14.11,NOTICIAS DE HOY NUEVAS 13 DE OCTUBRE 2017,Las Ultimas de HOY,22,2017-11-12T21:00:01.000Z,[none],195613,929,238,92,https://i.ytimg.com/vi/cgYhR-3QfhM/default.jpg,False,False,False,NOTICIAS DE HOY NUEVAS 13 DE OCTUBRE 2017,MX
56,mevdRfjbwH4,17.14.11,Leslie mar vs Mayela Without you - la voz Méxi...,Pablo Zarate,29,2017-11-13T05:11:11.000Z,[none],15814,91,5,14,https://i.ytimg.com/vi/mevdRfjbwH4/default.jpg,False,False,False,NaN,MX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375776,1ce456Nnkt8,18.13.06,BABYMETAL - Distortion (OFFICIAL),BABYMETAL,10,2018-05-07T14:59:03.000Z,[none],3371368,92738,2630,9840,https://i.ytimg.com/vi/1ce456Nnkt8/default.jpg,False,False,False,We delivered our new song Distortion as a surp...,GB
375840,fAIX12F6958,18.14.06,Bumblebee (2018) - Official Teaser Trailer - P...,Paramount Pictures,1,2018-06-05T07:00:01.000Z,[none],19864779,228670,16420,46318,https://i.ytimg.com/vi/fAIX12F6958/default.jpg,False,False,False,Every adventure has a beginning. Watch the off...,GB
375851,Y99Wj-NStok,18.14.06,Choco Mountain: The History of Mario Kart 64's...,Summoning Salt,20,2018-06-04T03:24:53.000Z,[none],929926,40563,776,3766,https://i.ytimg.com/vi/Y99Wj-NStok/default.jpg,False,False,False,https://www.twitch.tv/summoningsalthttps://twi...,GB
375910,wswvNZveNHc,18.14.06,Charmed (The CW) Trailer HD - 2018 Reboot,TV Promos,24,2018-05-17T16:07:29.000Z,[none],2201784,35149,16812,12894,https://i.ytimg.com/vi/wswvNZveNHc/default.jpg,False,False,False,"After the tragic death of their mother, three ...",GB
375914,bGW2eZGnznk,18.14.06,THE HAPPYTIME MURDERS Official Trailer (2018),Movie Trailers Source,1,2018-05-18T15:37:16.000Z,[none],607226,4531,715,869,https://i.ytimg.com/vi/bGW2eZGnznk/default.jpg,False,False,False,THE HAPPYTIME MURDERS Official Trailer Action...,GB

### 3. For each channel, determine the total number of views

In [9]:
total_views_per_channel = df_videos.groupby("channel_title")["views"].sum()
total_views_per_channel

channel_title
! 세상에 무슨일이                3942977
!!8時だよ面白ネタ大集合               50207
!BTS・TWICE まとめ               7310
!Los amorosos Virales¡       6069
!t Live                    240038
                           ...
５分でできる DIY                 272607
ＢＡＳＨｔｖ                     116292
Ｋのフィッシングちゃんねる               37165
ＷＡＪＯＩＫＡ                    424129
💜Sandrea                   347155
Name: views, Length: 37824, dtype: int64

In [10]:
total_views_per_channel = df_videos.groupby("channel_title")["views"].sum().reset_index()

total_views_per_channel.head(10)

            channel_title    views
0              ! 세상에 무슨일이  3942977
1           !!8時だよ面白ネタ大集合    50207
2          !BTS・TWICE まとめ     7310
3  !Los amorosos Virales¡     6069
4                 !t Live   240038
5               !内ラチの上を走れ    11528
6                   !島ちゃん  1061020
7                 !衝撃的な動画     9112
8                     # #     2318
9               # Milgame     1448

### 4. Save all rows with disabled comments and disabled ratings, or that have video_error_or_removed in a new dataframe called excluded, and remove those rows from the original dataframe.

In [11]:
df_videos_disabled = df_videos[df_videos["comments_disabled"] | df_videos["video_error_or_removed"]]
df_videos = df_videos.drop(df_videos_disabled.index)

### 5. Add a like_ratio column storing the ratio between the number of likes and of dislikes

In [13]:
df_videos["like_ratio"] = df_videos["likes"] / df_videos["dislikes"].replace(0, 1)
df_videos[["title", "likes", "dislikes", "like_ratio"]].head(10)

,title,likes,dislikes,like_ratio
0,Capítulo 12 | MasterChef 2017,4182,361,11.584488
1,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUN...,271,174,1.557471
2,LOUIS CKAGÓ - EL PULSO DE LA REPÚBLICA,10105,266,37.988722
3,Sismo de 6.7 sacude Costa Rica 12 Noviembre 2017,378,171,2.210526
4,DOG HACKS | MUSAS LESSLIE LOS POLINESIOS,57781,681,84.847283
5,Asi se sintio Terremoto en iraq al bordo de ir...,506,67,7.552239
6,La Resolana con el Capi | Programa 12 noviembr...,2277,69,33.000000
8,7 Niños Famosos Que No Supieron Adaptarse a La...,20155,912,22.099781
9,TOP: Los 7 libros infantiles más perturbadores...,83582,2194,38.095716
10,Franco Escamilla.- Tradiciones y Faitelson,23279,270,86.218519

### 6. Cluster the publish time into 10-minute intervals (e.g. from 02:20 to 02:30)

In [ ]:

df_videos["publish_time"] = pd.to_datetime(df_videos["publish_time"])

df_videos["publish_10min"] = df_videos["publish_time"].dt.floor("10min")

videos[["publish_time", "publish_10min"]].head(10)

/var/folders/7x/ltnfqklj08qcjshc7d8pkcd00000gn/T/ipykernel_16679/19327855.py:5: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  df_videos["publish_10min"] = df_videos["publish_time"].dt.floor("10T")

                publish_time             publish_10min
0  2017-11-13 06:06:22+00:00 2017-11-13 06:00:00+00:00
1  2017-11-13 05:11:58+00:00 2017-11-13 05:10:00+00:00
2  2017-11-13 17:00:02+00:00 2017-11-13 17:00:00+00:00
3  2017-11-13 03:47:10+00:00 2017-11-13 03:40:00+00:00
4  2017-11-13 19:17:48+00:00 2017-11-13 19:10:00+00:00
5  2017-11-12 20:17:38+00:00 2017-11-12 20:10:00+00:00
6  2017-11-13 07:00:03+00:00 2017-11-13 07:00:00+00:00
8  2017-11-12 19:54:12+00:00 2017-11-12 19:50:00+00:00
9  2017-11-12 21:14:44+00:00 2017-11-12 21:10:00+00:00
10 2017-11-12 19:30:02+00:00 2017-11-12 19:30:00+00:00

In [17]:
df_videos["publish_interval"] = (
    df_videos["publish_10min"].dt.strftime("%H:%M") 
    + " - " +
    (df_videos["publish_10min"] + pd.Timedelta(minutes=10)).dt.strftime("%H:%M")
)

df_videos[["publish_time", "publish_interval"]].head(10)

                publish_time publish_interval
0  2017-11-13 06:06:22+00:00    06:00 - 06:10
1  2017-11-13 05:11:58+00:00    05:10 - 05:20
2  2017-11-13 17:00:02+00:00    17:00 - 17:10
3  2017-11-13 03:47:10+00:00    03:40 - 03:50
4  2017-11-13 19:17:48+00:00    19:10 - 19:20
5  2017-11-12 20:17:38+00:00    20:10 - 20:20
6  2017-11-13 07:00:03+00:00    07:00 - 07:10
8  2017-11-12 19:54:12+00:00    19:50 - 20:00
9  2017-11-12 21:14:44+00:00    21:10 - 21:20
10 2017-11-12 19:30:02+00:00    19:30 - 19:40

Abbiamo trasformato l’orario di pubblicazione di ogni video in un intervallo di 10 minuti.  
Questo ci permette di raggruppare i video in fasce orarie più ampie e più facili da analizzare.

Per prima cosa abbiamo convertito la colonna `publish_time` in un formato datetime, per essere sicuri che Python la riconosca come un orario.

Successivamente abbiamo usato la funzione `dt.floor("10min")` per “arrotondare verso il basso” l’orario al suo intervallo di 10 minuti.  

Infine abbiamo creato una colonna opzionale `publish_interval` per mostrare l’intervallo in modo più chiaro, ad esempio `"06:20 - 06:30"`.  
Questo rende l’analisi dei tempi di pubblicazione più intuitiva e immediata.

### 7. For each interval, determine the number of videos, average number of likes and of dislikes.

In [21]:

interval_stats = df_videos.groupby("publish_10min").agg(
    number_of_videos = ("video_id", "count"),
    average_likes = ("likes", "mean"),
    average_dislikes = ("dislikes", "mean")
)


interval_stats.head(10)

                           number_of_videos  average_likes  average_dislikes
publish_10min
2006-07-23 08:20:00+00:00                 1     459.000000        152.000000
2007-03-05 16:20:00+00:00                 9     336.666667          2.000000
2007-06-25 06:50:00+00:00                12     579.833333         11.500000
2007-12-03 20:50:00+00:00                16     187.937500         15.687500
2008-01-07 21:20:00+00:00                10      99.900000          2.000000
2008-01-13 01:30:00+00:00                 2    1417.000000         49.500000
2008-02-12 20:20:00+00:00                 3    1985.666667        124.666667
2008-04-05 18:20:00+00:00                 4      46.000000          6.000000
2008-06-17 00:00:00+00:00                 4     469.000000          4.000000
2008-08-07 12:10:00+00:00                 3      78.333333          1.000000

### 8. For each tag, determine the number of videos. Notice that tags contains a string with several tags

In [18]:
# Setup tag column in our dataframe first
df_videos["tags"] = df_videos["tags"].str.split('|') # Split the string into array with '|' as the separator

# Explode dataframe so that each row wiill have one tag, it will duplicate rows with many tags
# This is the approach because it is useful when grouping by tags.
df_videos_tags_explode = df_videos.explode('tags')

In [19]:
# clean dataset by removing all extra characters such as double quotations (")
df_videos_tags_explode["tags"] = df_videos_tags_explode["tags"].str.replace('"', '')

In [20]:
df_videos_tags_explode["tags"].value_counts()

tags
[none]                                 36370
funny                                  14945
comedy                                 12303
2018                                   10991
news                                    6067
                                       ...
Rory Kramer Vision                         1
Rory Kramer                                1
The Chainsmokers Somebody Drew Love        1
Somedy Drew Love                           1
Chainsmokers Somebody                      1
Name: count, Length: 840346, dtype: int64

### 9. Find the tags with the largest number of videos

In [22]:
df_videos_tags_explode.groupby(by="tags")["views"].sum()

tags
                                                   357327734
 #Freeticket                                         1761155
 #Jaisimha                                           1761155
 #JanaSenaParty                                       582282
 #MahaaNews                                           440239
                                                     ...
😜😜                                                     31787
😥                                                      44089
😭 #résistancelamaindesqueezie ❤️                       19781
😭قفز عسكري الوحيد من الطائرة العسكرية الجزائرية      1234013
🤝 ZARBEX zahlt Schutzgeld!!!                           29535
Name: views, Length: 840346, dtype: int64

### 10. For each (tag, country) pair, compute average ratio likes/dislikes

In [10]:
# TO DO: UNCOMMENT CODE BELOW ONCE 5 5 IS FINISHED
# pd.DataFrame(df_videos_tags_explode.groupby(by=["tags","country"])["like_dislike_ratio"].mean()) <- Needs table from 5

### 11. For each (trending_date, country) pair, the video with the largest number of views

### 12. Divide trending_date into three columns: year, month, day

### 13. For each (month, country) pair, the video with the largest number of views

### 14. Read all json files with the video categories

### 15. For each country, determine how many videos have a category that is not assignable